# Generated by Django 2.2.4 on 2019-09-09 04:49

import apps.account.models
import conf.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, storage=conf.storage.OverwriteStorage(), upload_to=apps.account.models.User.upload_avatar_path, verbose_name='Uploaded avatar of profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
