# Generated by Django 2.2.4 on 2019-09-12 07:01

import apps.hero.models
import conf.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.FileField(blank=True, null=True, storage=conf.storage.OverwriteStorage(), upload_to=apps.hero.models.Hero.upload_human_path, verbose_name='Uploaded thumbnail of footballer')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hero_in_type', to='hero.HeroType')),
            ],
        ),
    ]
