# Generated by Django 2.2.4 on 2019-09-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='first_name',
        ),
        migrations.AddField(
            model_name='hero',
            name='attack_to_heal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='magic_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='magic_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='physical_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='physical_defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
