# Generated by Django 2.2.4 on 2019-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20190912_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='health',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='hero',
            name='mana',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='hero',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
