# Generated by Django 2.2.4 on 2019-09-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20190912_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='type',
        ),
        migrations.DeleteModel(
            name='HeroType',
        ),
    ]
