# Generated by Django 2.2.4 on 2019-09-09 07:44

import apps.club.models
import conf.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.FileField(blank=True, null=True, storage=conf.storage.OverwriteStorage(), upload_to=apps.club.models.Club.upload_clubs_path, verbose_name='Uploaded thumbnail of club')),
            ],
        ),
    ]
