# Generated by Django 2.2.4 on 2019-09-12 07:36

import apps.equipment.models
import conf.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.FileField(blank=True, null=True, storage=conf.storage.OverwriteStorage(), upload_to=apps.equipment.models.Equipment.upload_equipment_path, verbose_name='Uploaded thumbnail of equipment')),
                ('price', models.BigIntegerField(default=0)),
                ('physical_damage', models.IntegerField(default=0)),
                ('magic_damage', models.IntegerField(default=0)),
                ('physical_defence', models.IntegerField(default=0)),
                ('magic_defence', models.IntegerField(default=0)),
                ('attack_to_heal', models.IntegerField(default=0)),
                ('plus_health', models.IntegerField(default=500)),
                ('plus_mana', models.IntegerField(default=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
