# Generated by Django 2.2.4 on 2019-09-09 04:34

import apps.product.models
import conf.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('is_suggested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_suggested', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_categories', to='product.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('thumbnail', models.FileField(blank=True, null=True, storage=conf.storage.OverwriteStorage(), upload_to=apps.product.models.Product.upload_product_path, verbose_name='Uploaded thumbnail of product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categories', models.ManyToManyField(blank=True, to='product.ProductCategory')),
                ('features', models.ManyToManyField(blank=True, to='product.ProductFeature')),
            ],
        ),
    ]
